EXAMPLE: Make @axhxrx/json depend on nonexistent future version 0.1.1 of @axhxrx/ts (causing the tests to fail[1])
[1]: We can see the tests fail due to the version not existing on
JSR or in this monorepo:

➜  jsr-deno-nx-monorepo-test git:(main) ✗ deno test libs/jsr/@axhxrx/json
Warning Workspace member '@axhxrx/ts@0.1.0' was not used because it did not match '@axhxrx/ts@0.1.1'
    at file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/json/sortedStringify.ts:1:26
error: Could not find version of '@axhxrx/ts' that matches specified version constraint '0.1.1'
    at file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/json/sortedStringify.ts:1:26
➜  jsr-deno-nx-monorepo-test git:(main) ✗