Init new lib @axhxrx/ts with Deno[1]
[1]:

                            _____________________
                      ____||  MASON MARK (.COM)  |
                     []   ||      10.0.0.5       |  ____
                     |    ||     stud.local      | ___
                     |____||_____________________|
                      (o)   (o)            (o)(o)

_________________________________________________________________
➜  ts git:(main) ✗ deno init --lib
✅ Project initialized

Run these commands to get started

  # Run the tests
  deno test

  # Run the tests and watch for file changes
  deno task dev

  # Publish to JSR (dry run)
  deno publish --dry-run
➜  ts git:(main) ✗
➜  ts git:(main) ✗
➜  ts git:(main) ✗ deno test
Check file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/ts/mod_test.ts
running 1 test from ./mod_test.ts
addTest ... ok (0ms)

ok | 1 passed | 0 failed (2ms)

➜  ts git:(main) ✗
➜  ts git:(main) ✗
➜  ts git:(main) ✗ deno publish --dry-run
Check file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/ts/mod.ts
Checking for slow types in the public API...
Check file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/ts/mod.ts
error: Failed preparing 'ts'.

Caused by:
    Invalid package name, use '@<scope_name>/<package_name> format
➜  ts git:(main) ✗
➜  ts git:(main) ✗
➜  ts git:(main) ✗ # OK WE WILL FIX THAT IN NEXT COMMIT
➜  ts git:(main) ✗
➜  ts git:(main) ✗