EXAMPLE: show how the failed DNT solution breaks when working on an unpublished library version[1]
[1]: it anyway doesn't use the correct code, but this just shows
how it breaks when working with unpublished library versions:

➜  dnt-legaprise-builder git:(main) ✗ deno -A mod.ts -i ../json/mod.ts -o ../../../../built/@axhxrx/json
[dnt] Transforming...
error: Uncaught (in promise) "Could not find version of '@axhxrx/ts' that matches specified version constraint '0.1.2'\n    at file:///Volumes/STUFF/CODE/jsr-deno-nx-monorepo-test/libs/jsr/@axhxrx/json/sortedStringify.ts:1:26 (jsr:@axhxrx/ts@0.1.2)"
➜  dnt-legaprise-builder git:(main) ✗